# Generated by Django 4.2.2 on 2023-08-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
