# Generated by Django 4.2.2 on 2023-08-26 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=230, unique=True)),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('image_url', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('alt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('keywords', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'News Articles',
                'ordering': ['-updated_on', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=230, unique=True)),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('image_url', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('alt', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('keywords', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'posts',
                'ordering': ['-updated_on', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SubscribedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('subscribe_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Subscribed users',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Waiting Approval'), ('published', 'Approved')], default='draft', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(auto_now=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('reply_created_on', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomments', to='blog.post')),
            ],
            options={
                'ordering': ['-approved_on'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Waiting Approval'), ('published', 'Approved')], default='draft', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(auto_now=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('reply_created_on', models.DateTimeField(auto_now=True)),
                ('newsarticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newscomments', to='blog.newsarticle')),
            ],
            options={
                'ordering': ['-approved_on'],
            },
        ),
    ]
